### ISSUE TITLE
PingLogger 2.4.0.34 Start Failure

### ISSUE THREAD

**Issue by jogrothe** [vouksh/PingLogger#15]
Since latest Windows Update PingLogger fails to start up.

![20210313-0930 PingLogger 2 4 0 34 Start Failure](https://user-images.githubusercontent.com/38055293/111025256-39795580-83e3-11eb-8de4-a784c9ea1b71.jpg)

ADDITIONAL INFOS

**System**
GERMAN Windows 10, Version 20H2 with latest available updates
dotnet-sdk-5.0.201-win-x64.exe installed

**Application**
PingLogger 2.4.0.34 installed via PingLogger-Setup.msi

**PingLogger-20210313.log**
```
[09:54:20.122 Information] (PrimaryUIThread) Application start, version 2.4.0.34
[09:54:20.155 Information] (PrimaryUIThread) Application is running from directory C:\Users\{user}\PingLogger\
[09:54:20.155 Information] (PrimaryUIThread) Using C:\Users\{user}\PingLogger\ to save config and logs
[09:54:20.165 Information] (PrimaryUIThread) Found existing config.dat, reading file
[09:54:20.183 Information] (PrimaryUIThread) Reading hosts configuration
[09:54:20.269 Information] (PrimaryUIThread) Reading application configuration
[09:54:24.520 Fatal] (PrimaryUIThread) A fatal unhandled exception occurred
System.Net.WebException: The remote server returned an error: (404) The specified resource does not exist..
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.GetWebResponseTaskAsync(WebRequest request)
   at System.Net.WebClient.DownloadBitsAsync(WebRequest request, Stream writeStream, AsyncOperation asyncOp, Action`3 completionDelegate)
   at PingLogger.Util.CheckForUpdates()
   at PingLogger.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at PingLogger.App.Main()
```

**Comment by theovencook** [comment]
Same here.
@vouksh

**Comment by vouksh** [comment]
Apologies. One of my CI/CD pipelines broke. I'll do a manual build and publish it this weekend. Been super busy with work and this project has fallen to the wayside. 

I honestly had no idea people were actually using this, since I've had so little feedback.

**Comment by vouksh** [comment]
@theovencook @jogrothe I discovered the issue, the 2.4 version is using my old Azure account for blob storage. I've got an alternate host setup, I just need to get a build together pushed to GitHub. I Might be breaking this project off into a legacy version (sticking at 2.4) and keeping the cross-platform v3.0 in a different repo. I'll have a working version sometime this weekend. I apologize for the time it's taking.

**Comment by theovencook** [comment]
@vouksh Sweet, thanks..! 
Appreciated.

**Comment by vouksh** [comment]
@theovencook @jogrothe I split v2.4 over to its own legacy project at https://github.com/vouksh/PingLogger-Legacy
I published the release files. If you still have issues with that version, open a new issue on that project. Closing this issue for now.
